apiVersion: apps/v1
kind: Deployment
metadata:
  name: endpoint-gateway
  namespace: default
spec:
  selector:
    matchLabels:
      app: endpoint-gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: endpoint-gateway
    spec:
      containers:
        - name: nginx
          image: evankrul/nginx-gateway:regular
#          image: vahidmostofi/nginx-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9099 # if you change this, you need to change all 9099s in this file
          env:
            - name: TELEGRAF_SYSLOG_SERVER
              value: "localhost:6514"
            - name: PORT
              value: "9099"
            - name: PROXY_PASS_URL
              value: "http://cgroup-monitor-sc:2335"
          resources:
            requests:
              memory: "700Mi"
              cpu: 0.5
            limits:
              memory: "700Mi"
              cpu: 0.5
        - name: telegraf-agent
          image: vahidmostofi/telegraf-agent:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8125
            - containerPort: 8092
            - containerPort: 8094
            - containerPort: 6514
          env:
            - name: INFLUXDB_URL
              valueFrom:
                secretKeyRef:
                  name: influxdb-secrets
                  key: INFLUXDB_URL
            - name: INFLUXDB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: influxdb-secrets
                  key: INFLUXDB_TOKEN
            - name: INFLUXDB_ORG
              valueFrom:
                secretKeyRef:
                  name: influxdb-secrets
                  key: INFLUXDB_ORG
            - name: INFLUXDB_BUCKET
              valueFrom:
                secretKeyRef:
                  name: influxdb-secrets
                  key: INFLUXDB_BUCKET
            - name: NGINX_DEFAULT_STATS_URL
              value: "http://localhost:9099/nginx_status"
            - name: SYSLOG_SERVER_PORT
              value: "6514"
          resources:
            requests:
              memory: "700Mi"
              cpu: 0.5
            limits:
              memory: "700Mi"
              cpu: 0.5

---
apiVersion: v1
kind: Service
metadata:
  name: endpoint-gateway
  namespace: default
spec:
  selector:
    app: endpoint-gateway
  ports:
    - port: 9099
      targetPort: 9099
      protocol: TCP
  type: LoadBalancer

