apiVersion: v1

kind: ConfigMap
metadata:
  name: k8s-monitor-config
  namespace: bookstore
data:
  telegraf.conf: |+
    # Telegraf Configuration

    # Global tags can be specified here in key="value" format.
    [global_tags]
      
    # Configuration for telegraf agent
    [agent]
      interval = "10s"
      round_interval = true
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      collection_jitter = "0s"
      flush_interval = "10s"
      flush_jitter = "0s"
      precision = ""
      debug = true
      hostname = ""
      omit_hostname = false

    # Configuration for sending metrics to InfluxDB
    [[outputs.influxdb_v2]]
      urls = ["${INFLUXDB_URL}"]
      token = "${INFLUXDB_TOKEN}"
      organization = "${INFLUXDB_ORG}"
      bucket = "${INFLUXDB_BUCKET}"
      insecure_skip_verify = true

    # Read metrics from the Kubernetes api
    [[inputs.kube_inventory]]
      ## URL for the Kubernetes API
      url = "https://${KUBERNETES_SERVICE_HOST}"
      namespace = "bookstore"
      insecure_skip_verify = true

    # Run executable as long-running input plugin
    [[inputs.execd]]
      ## Program to run as daemon
      command = ["/report-metrics.out"]
      signal = "none"
      restart_delay = "10s"
      data_format = "influx"

    [[outputs.file]]
      files = ["stdout"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: bookstore
  name: monitorer
automountServiceAccountToken: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: bookstore
  name: k8s-monitor-deployment
spec:
  selector:
    matchLabels:
      app: k8s-monitor
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: k8s-monitor
    spec:
      serviceAccountName: monitorer
      automountServiceAccountToken: true
      containers:
        - image: vahidmostofi/telegraf-metrics-reporter:latest
          name: telegraf
          volumeMounts:
            - mountPath: /etc/telegraf/telegraf.conf
              name: k8s-monitor-config
              subPath: telegraf.conf
              readOnly: true
          envFrom:
            - secretRef:
                name: influxdb-secrets
          env:
            - name: METRICS_MONITOR_K8S_NAMESPACE
              value: bookstore
      volumes:
        - name: k8s-monitor-config
          configMap:
            name: k8s-monitor-config
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: bookstore
  name: influx:telegraf:viewer
  labels:
    rbac.authorization.k8s.io/aggregate-view-telegraf: "true"
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes", "nodes"]
    verbs: ["get", "list"]
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: bookstore
  name: influx:telegraf
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        rbac.authorization.k8s.io/aggregate-view-telegraf: "true"
    - matchLabels:
        rbac.authorization.k8s.io/aggregate-to-view: "true"
rules: [] # Rules are automatically filled in by the controller manager.
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  namespace: bookstore
  name: influx:telegraf:viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: influx:telegraf
subjects:
  - kind: ServiceAccount
    name: monitorer
    namespace: bookstore
