apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: bookstore
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: gateway
    spec:
      terminationGracePeriodSeconds: 13
      containers:
        - name: app
          image: vahidmostofi/bookstore_entry
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5
            failureThreshold: 3
          env:
            - name: WorkerCount
              value: "1"
            - name: JWT_KEY
              value: "someKeyIsGoodAndSomeOfThemBNoGEo1ioD!"
            - name: JAEGER_SERVICE_NAME
              value: "gateway"
            - name: JAEGER_COLLECTOR_HOST
              valueFrom:
                configMapKeyRef:
                  name: jaeger-config
                  key: JAEGER_COLLECTOR_HOST
            - name: JAEGER_COLLECTOR_PORT
              valueFrom:
                configMapKeyRef:
                  name: jaeger-config
                  key: JAEGER_COLLECTOR_PORT
            - name: JAEGER_AGENT_HOST
              valueFrom:
                configMapKeyRef:
                  name: jaeger-config
                  key: JAEGER_AGENT_HOST
            - name: JAEGER_AGENT_PORT
              valueFrom:
                configMapKeyRef:
                  name: jaeger-config
                  key: JAEGER_AGENT_PORT
            - name: SAMPELLING_PROB
              valueFrom:
                configMapKeyRef:
                  name: jaeger-config
                  key: SAMPELLING_PROB
          resources:
            requests:
              memory: "512Mi"
              cpu: 0.5
            limits:
              memory: "512Mi"
              cpu: 0.5
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: bookstore
spec:
  selector:
    app: gateway
  ports:
    - port: 9080
      targetPort: 8080
      protocol: TCP
  type: NodePort
