apiVersion: apps/v1
kind: Deployment
metadata:
  name: books
spec:
  selector:
    matchLabels:
      app: books
  replicas: 1
  template:
    metadata:
      labels:
        app: books
    spec:
      shareProcessNamespace: true
      containers:
        - name: app
          image: evankrul/bookstore_book:in_mem.v.1
#          imagePullPolicy: Always
          ports:
            - containerPort: 3009
#          readinessProbe:
#            httpGet:
#              path: /health
#              port: 3009
#            initialDelaySeconds: 5
#            periodSeconds: 5
#            successThreshold: 1
#            timeoutSeconds: 5
#            failureThreshold: 3
          env:
            - name: WorkerCount
              value: "50"
            - name: JAEGER_SERVICE_NAME
              value: "books"
            - name: PORT
              value: "3009"
            - name: MONGODB_URL
              value: "mongodb://mongo:27017/bookstoreDB"
            - name: JAEGER_COLLECTOR_HOST
              valueFrom:
                configMapKeyRef:
                  name: jaeger-config
                  key: JAEGER_COLLECTOR_HOST
            - name: JAEGER_COLLECTOR_PORT
              valueFrom:
                configMapKeyRef:
                  name: jaeger-config
                  key: JAEGER_COLLECTOR_PORT
            - name: JAEGER_AGENT_HOST
              valueFrom:
                configMapKeyRef:
                  name: jaeger-config
                  key: JAEGER_AGENT_HOST
            - name: JAEGER_AGENT_PORT
              valueFrom:
                configMapKeyRef:
                  name: jaeger-config
                  key: JAEGER_AGENT_PORT
            - name: SAMPELLING_PROB
              valueFrom:
                configMapKeyRef:
                  name: jaeger-config
                  key: SAMPELLING_PROB
          resources:
            requests:
              memory: "512Mi"
              cpu: 0.5
            limits:
              memory: "512Mi"
              cpu: 0.5
          volumeMounts:
            - name: pid-flag-volume
              mountPath: /etc/pid_flag
        - name: cgroup-monitor-sc
          image: evankrul/cgroup-sc:prom.v.1.2
          ports:
            - containerPort: 3029
              name: metrics
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
          env:
            - name: PORT
              value: "3029"
          resources:
            requests:
              cpu: "15m"
              memory: "40Mi"
            limits:
              cpu: "15m"
              memory: "40Mi"
          volumeMounts:
            - name: pid-flag-volume
              mountPath: /etc/pid_flag_sc
      volumes:
        - name: pid-flag-volume
          configMap:
            name: pid-flag-config-map-book
---
#Cgroup config map
kind: ConfigMap
apiVersion: v1
metadata:
  name: pid-flag-config-map-book
data:
  pid_flag: books
---
apiVersion: v1
kind: Service
metadata:
  name: books
spec:
  selector:
    app: books
  ports:
    - name: books
      port: 3009
      targetPort: 3009
    - name: metrics
      port: 3029
      targetPort: 3029
  type: ClusterIP