apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-gateway
spec:
  selector:
    matchLabels:
      app: metrics-gateway
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: metrics-gateway
    spec:
      terminationGracePeriodSeconds: 13
      containers:
        - name: app
          image: evankrul/bookstore_gateway:in_mem.v.3
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5000
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 5000
            failureThreshold: 3000
          # lifecycle:
          #   preStop:
          #     exec:
          #       command:
          #         - /bin/sh
          #         - -c
          #         - echo "Goodbye at" `date`
          env:
            - name: WorkerCount
              value: "10"
            - name: JWT_KEY
              value: "someKeyIsGoodAndSomeOfThemBNoGEo1ioD!"
            - name: JAEGER_SERVICE_NAME
              value: "metrics-gateway"
            - name: JAEGER_COLLECTOR_HOST
              valueFrom:
                configMapKeyRef:
                  name: jaeger-config
                  key: JAEGER_COLLECTOR_HOST
            - name: JAEGER_COLLECTOR_PORT
              valueFrom:
                configMapKeyRef:
                  name: jaeger-config
                  key: JAEGER_COLLECTOR_PORT
            - name: JAEGER_AGENT_HOST
              valueFrom:
                configMapKeyRef:
                  name: jaeger-config
                  key: JAEGER_AGENT_HOST
            - name: JAEGER_AGENT_PORT
              valueFrom:
                configMapKeyRef:
                  name: jaeger-config
                  key: JAEGER_AGENT_PORT
            - name: SAMPELLING_PROB
              valueFrom:
                configMapKeyRef:
                  name: jaeger-config
                  key: SAMPELLING_PROB
          resources:
            requests:
              memory: "3000Mi"
#              memory: "512Mi"
              cpu: 2.5
            limits:
              memory: "3000Mi"
#              memory: "512Mi"
              cpu: 2.5
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-gateway #this will be the Domain name
spec:
  selector:
    app: metrics-gateway
  ports:
    - name: metrics-gateway-port
      port: 9091
      targetPort: 8080
  type: LoadBalancer
