apiVersion: v1

kind: Secret
metadata:
  name: influxdb-secrets
type: Opaque
stringData:
  INFLUXDB_URL: "http://influx.krul.ca"
  INFLUXDB_TOKEN: "rootpass"
  INFLUXDB_ORG: "evan"
  INFLUXDB_BUCKET: "metrics"