package constants

const CONFIG_INFLUXDB_URL = "CONFIG_INFLUXDB_URL"
const CONFIG_INFLUXDB_TOKEN = "CONFIG_INFLUXDB_TOKEN"
const CONFIG_INFLUXDB_BUCKET = "CONFIG_INFLUXDB_BUCKET"
const CONFIG_INFLUXDB_ORG = "CONFIG_INFLUXDB_ORG"

const CONFIG_RESOURCE_FILTERS = "CONFIG_RESOURCE_FILTERS" // needs to be map[string]map[string]interface{}