package constants

const CONFIG_INFLUXDB_URL = "CONFIG_INFLUXDB_URL" // there should be more than one bucket for different aggregators
const CONFIG_INFLUXDB_TOKEN = "CONFIG_INFLUXDB_TOKEN" // there should be more than one bucket for different aggregators
const CONFIG_INFLUXDB_BUCKET = "CONFIG_INFLUXDB_BUCKET" // there should be more than one bucket for different aggregators
const CONFIG_INFLUXDB_ORG = "CONFIG_INFLUXDB_ORG" // there should be more than one bucket for different aggregators

const CONFIG_RESOURCE_FILTERS = "CONFIG_RESOURCE_FILTERS" // needs to be map[string]map[string]interface{}
const CONFIG_ENDPOINTS_FILTERS = "CONFIG_ENDPOINTS_FILTERS" // needs to be map[string]map[string]interface{}

const CONFIG_ENDPOINTS_2_RESOURCES = "CONFIG_ENDPOINTS_2_RESOURCES"
const CONFIG_SYSTEM_STRUCTURE_AGGREGATOR_TYPE = "CONFIG_SYSTEM_STRUCTURE_AGGREGATOR_TYPE" // predefined

const CONFIG_VERSION_CODE = "CONFIG_VERSION_CODE"

const CONFIG_SYSTEM_NAMESPACE = "CONFIG_SYSTEM_NAMESPACE"
const CONFIG_SYSTEM_DEPLOYMENTS_TO_MANAGE = "CONFIG_SYSTEM_DEPLOYMENTS_TO_MANAGE" // []string

const CONFIG_VALIDATION_TOTAL_MEMORY = "CONFIG_VALIDATION_TOTAL_MEMORY"
const CONFIG_VALIDATION_TOTAL_CPU = "CONFIG_VALIDATION_TOTAL_CPU"

const CONFIG_VALIDATION_USE_CACHE = "CONFIG_VALIDATION_USE_CACHE" // bool
const CONFIG_CONFIGURATION_DATABASE_TYPE = "CONFIG_CONFIGURATION_DATABASE_TYPE"
const CONFIG_CONFIGURATION_DATABASE_S3_REGION = "CONFIG_CONFIGURATION_DATABASE_S3_REGION"
const CONFIG_CONFIGURATION_DATABASE_S3_BUCKET = "CONFIG_CONFIGURATION_DATABASE_S3_BUCKET"

const CONFIG_WAIT_TIMES = "CONFIG_WAIT_TIMES" // of type internal/autocfg/manager.go/WaitTimes struct

const CONFIG_ENDPOINTS_AGGREGATOR_TYPE = "CONFIG_ENDPOINTS_AGGREGATOR_TYPE"
const CONFIG_USAGE_AGGREGATOR_TYPE = "CONFIG_USAGE_AGGREGATOR_TYPE"

const CONFIG_RESULTS_PREFIX_PATH = "constants.CONFIG_RESULTS_PREFIX_PATH" // TODO do we need this? shouldn't we move to s3?